/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BatteryIndicator.java
 *
 * Created on Jan 3, 2011, 1:30:53 AM
 */
package org.smnirven.rover.pc;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author smnirven
 */
public class BatteryIndicator extends javax.swing.JPanel {

    private Image img;

    private final Image FULL_BATTERY = new ImageIcon("~/Desktop/battery_full.png").getImage();
    private final Image THREE_QUARTER_BATTERY = new ImageIcon("~/Desktop/battery_three_quarters.png").getImage();
    
    /** Creates new form BatteryIndicator */
    public BatteryIndicator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(370, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public void paintComponent(Graphics g) {
        g.drawImage(img, 0, 0, null);
    }

    public void setFullBattery() {
        this.img = FULL_BATTERY;
        this.repaint();
    }

    public void setThreeQuarterBattery() {
        this.img = THREE_QUARTER_BATTERY;
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
